services:
    database:
        image: postgres
        container_name: docker_postgres
        volumes:
            - /data/postgresql:/var/lib/pgsql/15/
            - /data/postgresql/data:/var/lib/pgsql/15/data/
        ports:
            - 5432:5432
        restart: always
        
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: docker_db
